<?php
  $lang = array(
    // Header
    'Home' => 'الصفحة الريئسية' ,
    'About' => 'About' ,
    'Work' => 'Work' ,
    'Blog' => 'Blog' ,
    'Contact' => 'Contact',
    'LogIn' => 'تسجيل الدخول',
    'Menu' => 'القائمة',
    'ControlPanel' => 'لوحة التحكم',
    'Employees' => 'الموظفين',
    'Floors' => 'الطوابق',
    'Features' => 'الميزات',
    'Services' => 'الخدمات',
    'Clients' => 'الزبائن',
    'Logout' => 'تسجيل الخروج',
    'SignIn' => 'نافذة التسجيل',
    'ChangePassword' => 'تغير كلمة المرور',
    'SiteStyle' => 'نمط الموقع',
    'SiteSettings' => 'إعدات الموقع',

    // Admin Index Page
    'Settings' => 'الإعدادات',
    'Total' => 'مجموع ',
    'MoreDetails' => 'المزيد من التفاصيل',

    // settings And Processes
    'Phone' => 'هاتف',
    'Email' => 'بريد الالكتروني',
    'MyProfile' => 'الملف الشخصي',
    'Show' => 'عرض',
    'Edit' => 'تعديل',
    'Delete' => 'حذف',
    'Block' => 'حظر',
    'Add' => 'إضافة',
    'TableTheme' => 'سمات الجدول',
    'SiteInformation' => 'معلومات الموقع',
    'Manage' => 'إدارة ',
    'First' => 'الأول',
    'Next' => 'التالي',
    'Last' => 'الأخير',
    'cell' => 'خلية',
    'ChoosePageColor' => 'Choose Page Color',
    'ChooseElementColor' => 'Choose Element Color',
    'ChooseTextPrimaryColor' => 'Choose Text Primary Color',
    'ChooseTextSecondaryColor' => 'Choose Text Secondary Color',
    'ChooseInputBoxShadowColor' => 'Choose Input And BoxShadow Color',
    'ChooseSelectColor' => 'Choose Select Color',
    'ChooseYourLogo' => 'Choose Your Logo',
    'EnglishHotelName' => 'اسم الفندق الأجنبي',
    'ArabicHotelName' => 'اسم الفندق العربي',
    'ChooseYourColor' => 'Choose Your Color',

    // Admin Floors Page
    'Floor' => 'طابق',
    'FloorId' => 'رقم الطابق',
    'FlatCount' => 'عدد الشقق',
    'AddedBy' => 'أضيف من قبل',
    'Processes' => 'العمليات',
    'NewFloor' => 'طابق جديد',
    'RemoveAFloor' => 'حذف الطابق',
    'Warning:AreYouSureAboutThat' => 'تحذير: هل أنت متأكد من ذلك',
    'AddNow' => 'أضف الآن',

    // Flat Admin Page
    'Flats' => 'الشقق',
    'FlatId' => 'رقم الشقة',
    'RoomsCount' => 'عدد الغرف',
    'View' => 'الإطلالة',
    'FlatArea' => 'مساحة الشقة',
    'NewFlat' => 'شقة جديدة',
    'North' => 'الشمال',
    'East' => 'الشرق',
    'South' => 'الجنوب',
    'West' => 'الغرب',
    'NorthEast' => 'شمال شرق',
    'EastSouth' => 'جنوب شرق',
    'SouthWest' => 'جنوب غرب',
    'WestNorth' => 'شمال غرب',
    'MainImage' => 'الصورة الريئسية',
    'OtherImage' => 'صور ملحقة',
    'Close' => 'إغلاق',
    'Save' => 'حفظ',
    'Warning' => 'تحذير',
    'Quantity' => 'الكمية',
    'Warning:NoHotelFeaturesHaveBeenIntroducedYet' => 'تحذير: لم يتم إدخال الميزات الأساسية للفندق',
    'FlatFeatures:' => 'ميزات الشقة:',
    'Rooms' => 'الغرف',
    'Bathrooms' => 'Bathrooms',
    'Beds' => 'Beds',

    // Features Admin Page
    'NewFeature' => 'ميزة جديدة',
    'AddFeature' => 'إضافة ميزة',
    'EditFeature' => 'تعديل الميزة',
    'FeatureId' => 'رقم الميزة',
    'FeatureName' => 'اسم الميزة',
    'Details' => 'التفاصيل',
    'Price' => 'السعر',
    'Room' => 'غرفة',
    'Bath' => 'حمام',
    'Bed' => 'سرير',
    'TV' => 'تلفاز',
    'AC' => 'مكيف',
    'Stove' => 'غاز',
    'Oven' => 'فرن',
    'Fridge' => 'براد',
    'Laundry' => 'غسالة',
    'Cooler' => 'مبرد',
    'ThisFeatureIsExsist' => 'هذه الميزة موجودة',
    'TheFeatureUsedInTheFlatCannotBeDeleted' => 'لا يمكن حذف هذه الميزة لأنها مضافة لشقق',

    // Employees Page
    'EmpId' => 'رقم الموظف',
    'NewEmployee' => 'موظف جديد',
    'EditEmployee' => 'تعديل موظف',
    'ThisUserNameIsExsist' => 'هذا الحساب موجود',

    // Services Page
    'ServicesId' => 'رقم الخدمة',
    'ServiceName' => 'اسم الخدمة',
    'NewService' => 'خدمة جديدة',

    // LogIn Page
    'UserName' => 'اسم المستخدم',
    'Password' => 'كلمة المرور',
    'Sorry:ThereIsAnErrorInTheUserNameOrPassword' => 'عذرا: هناك خطأ في اسم المستخدم أو كلمة المرور',

    // NotFound Page
    'notFound' => 'غير موجود',
    'Error' => 'خطأ',
    'GoBack' => 'رجوع للخلف',
    'ThePageYouWereLookingForDoesNotExist,TheAddressMayBeMisspelled,OrThePageMayHaveBeenMovedOrDeleted.' => 'الصفحة التي كنت تبحث عنها غير موجودة أو ربما أخطأت في كتابة العنوان أو ربما تكون الصفحة قد نُقِلت أو حُذِفت.',
    'ThePageDoesNotExist' => 'الصفحة غير موجودة',

    // Footer
    'HotelName' => 'دارنا أوتيل',
    'InformationAboutTheCompany' => 'معلومات عن الشركة',
    'Help' => 'مساعدة',
    'InformationOffice' => 'المكتب الاعلامي',
    'InvestorRelations' => 'علاقات المستثمرين',
    'LearnHowAWebsiteWorks' => 'تعرف على كيفية عمل موقع ',
    'TermsAndConditions' => 'الشروط و الاحكام',
    'LegalInformation' => 'المعلومات القانونية ',
    'PrivacyNotice' => 'إخطار الخصوصية',
    'SiteMap' => 'خريطة الموقع',
    'Copyrights' => 'حقوق ملكية',
    'AllRightsAreSave' => 'جميع الحفوف محفوظة',

    //Table
    'Search' => 'بحث',
    'ElemnetsOnEachPage' => 'عناصر بكل صفحة',
    'ThereAreNoResult' => 'لا يوجد نتائج',
    'From' => 'من',
    'OutOf' => 'من أصل',
    'Records' => 'سجلات',
    'Searched' => 'تم البحث فيها',
  );
?>