<?php
  $lang = array(
    // Header
    'Home' => 'Home' ,
    'About' => 'About' ,
    'Work' => 'Work' ,
    'Blog' => 'Blog' ,
    'Contact' => 'Contact',
    'LogIn' => 'LogIn',
    'Menu' => 'Menu',
    'ControlPanel' => 'Control Panel',
    'Employees' => 'Employees',
    'Floors' => 'Floors',
    'Features' => 'Features',
    'Services' => 'Services',
    'Clients' => 'Clients',
    'Logout' => 'Logout',
    'SignIn' => 'Sign In',
    'ChangePassword' => 'Change Password',
    'SiteStyle' => 'Site Style',
    'SiteSettings' => 'Site Settings',

    // Admin Index Page
    'Settings' => 'Settings',
    'Total' => 'Total ',
    'MoreDetails' => 'More Details',

    // settings And Processes
    'Phone' => 'Phone',
    'Email' => 'Email',
    'MyProfile' => 'My Profile',
    'Show' => 'Show',
    'Edit' => 'Edit',
    'Delete' => 'Delete',
    'Block' => 'Block',
    'Add' => 'Add',
    'TableTheme' => 'Table Theme',
    'SiteInformation' => 'Site Information',
    'Manage' => 'Manage ',
    'First' => 'First',
    'Next' => 'Next',
    'Last' => 'Last',
    'cell' => 'cell',
    'ChoosePageColor' => 'Choose Page Color',
    'ChooseElementColor' => 'Choose Element Color',
    'ChooseTextPrimaryColor' => 'Choose Text Primary Color',
    'ChooseTextSecondaryColor' => 'Choose Text Secondary Color',
    'ChooseInputBoxShadowColor' => 'Choose Input And BoxShadow Color',
    'ChooseSelectColor' => 'Choose Select Color',
    'ChooseYourLogo' => 'Choose Your Logo',
    'EnglishHotelName' => 'English Hotel Name',
    'ArabicHotelName' => 'Arabic Hotel Name',
    'ChooseYourColor' => 'Choose Your Color',

    // Admin Floors Page
    'Floor' => 'Floor',
    'FloorId' => 'Floor ID',
    'FlatCount' => 'Flat Count',
    'AddedBy' => 'Added By',
    'Processes' => 'Processes',
    'NewFloor' => 'New Floor',
    'RemoveAFloor' => 'Remove A Floor',
    'Warning:AreYouSureAboutThat' => 'Warning: Are You Sure About That',
    'AddNow' => 'Add Now',

    // Flat Admin Page
    'Flats' => 'Flats',
    'FlatId' => 'Flat ID',
    'RoomsCount' => 'Rooms Count',
    'View' => 'View',
    'FlatArea' => 'Flat Area',
    'NewFlat' => 'New Flat',
    'North' => 'North',
    'East' => 'East',
    'South' => 'South',
    'West' => 'West',
    'NorthEast' => 'North East',
    'EastSouth' => 'East South',
    'SouthWest' => 'South West',
    'WestNorth' => 'West North',
    'MainImage' => 'Main Image',
    'OtherImage' => 'Other Image',
    'Close' => 'Close',
    'Save' => 'Save',
    'Warning' => 'Warning',
    'Quantity' => 'Quantity',
    'Warning:NoHotelFeaturesHaveBeenIntroducedYet' => 'Warning: No Hotel Features Have Been Introduced Yet',
    'FlatFeatures:' => 'Flat Features:',
    'Rooms' => 'Rooms',
    'Bathrooms' => 'Bathrooms',
    'Beds' => 'Beds',

    // Features Admin Page
    'NewFeature' => 'New Feature',
    'AddFeature' => 'Add Feature',
    'EditFeature' => 'Edit Feature',
    'FeatureId' => 'Feature ID',
    'FeatureName' => 'Feature Name',
    'Details' => 'Details',
    'Price' => 'Price',
    'Room' => 'Room',
    'Bath' => 'Bath',
    'Bed' => 'Bed',
    'TV' => 'TV',
    'AC' => 'AC',
    'Stove' => 'Stove',
    'Oven' => 'Oven',
    'Fridge' => 'Fridge',
    'Laundry' => 'Laundry',
    'Cooler' => 'Cooler',
    'ThisFeatureIsExsist' => 'This Feature Is Exsist',
    'TheFeatureUsedInTheFlatCannotBeDeleted' => 'The Feature Used In The Flat Cann\'t Be Deleted',

    // Employees Page
    'EmpId' => 'Employee ID',
    'NewEmployee' => 'New Employee',
    'EditEmployee' => 'Edit Employee',
    'ThisUserNameIsExsist' => 'This UserName Is Exsist',

    // Services Page
    'ServicesId' => 'Services Id',
    'ServiceName' => 'Service Name',
    'NewService' => 'New Service',

    // LogIn Page
    'UserName' => 'UserName',
    'Password' => 'Password',
    'Sorry:ThereIsAnErrorInTheUserNameOrPassword' => 'Sorry: There Is An Error In The UserName Or Password',

    // NotFound Page
    'notFound' => 'Not Found',
    'Error' => 'Error',
    'GoBack' => 'Go Back',
    'ThePageYouWereLookingForDoesNotExist,TheAddressMayBeMisspelled,OrThePageMayHaveBeenMovedOrDeleted.' => 'The Page You Were Looking For Does Not Exist, The Address May Be Misspelled, Or The Page May Have Been Moved Or Deleted.',
    'ThePageDoesNotExist' => 'The Page Does Not Exist',

    // Footer
    'HotelName' => 'Daarna Hotel',
    'InformationAboutTheCompany' => 'information about the company',
    'Help' => 'Help',
    'InformationOffice' => 'Information Office',
    'InvestorRelations' => 'Investor Relations',
    'LearnHowAWebsiteWorks' => 'Learn How A Website Works',
    'TermsAndConditions' => 'Terms And Conditions',
    'LegalInformation' => 'Legal Information',
    'PrivacyNotice' => 'Privacy Notice',
    'SiteMap' => 'Site Map',
    'Copyrights' => 'Copyrights',
    'AllRightsAreSave' => 'All Rights Are Save',

    //Table
    'Search' => 'Search',
    'ElemnetsOnEachPage' => 'Elemnets On Each Page',
    'ThereAreNoResult' => 'There Are No Result',
    'From' => 'From',
    'OutOf' => 'Out Of',
    'Records' => 'Records',
    'Searched' => 'Searched',
  );
?>